"""add queue

Revision ID: 0e916328282d
Revises: f4ddf75333f7
Create Date: 2020-10-26 12:01:57.381374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e916328282d'
down_revision = 'f4ddf75333f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
