"""Init

Revision ID: 17b4ca2fcbc7
Revises: 0e916328282d
Create Date: 2020-10-27 12:27:52.461669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b4ca2fcbc7'
down_revision = '0e916328282d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_message', sa.Column('marker', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_message', 'marker')
    # ### end Alembic commands ###
