"""add queue

Revision ID: 21bc3fcd1b7b
Revises: 712e55fe5f52
Create Date: 2020-10-26 11:59:30.620779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bc3fcd1b7b'
down_revision = '712e55fe5f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
