"""add queue

Revision ID: 2e00c892127b
Revises: 826265544ba3
Create Date: 2020-10-26 11:58:57.822744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e00c892127b'
down_revision = '826265544ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_typing_time', sa.DateTime(), nullable=True),
    sa.Column('message_time', sa.DateTime(), nullable=True),
    sa.Column('pre_message', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('message_point', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_message')
    # ### end Alembic commands ###
