"""add queue

Revision ID: 32ff98e119c8
Revises: c9f4818e2073
Create Date: 2020-10-26 11:59:19.015258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ff98e119c8'
down_revision = 'c9f4818e2073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
