"""add queue

Revision ID: 712e55fe5f52
Revises: 32ff98e119c8
Create Date: 2020-10-26 11:59:24.028645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712e55fe5f52'
down_revision = '32ff98e119c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
