"""add referals

Revision ID: 8eeef9a759ea
Revises: e2736e27c129
Create Date: 2020-10-28 09:21:36.156667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eeef9a759ea'
down_revision = 'e2736e27c129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_message', sa.Column('referal_need', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('referal_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'referal_quantity')
    op.drop_column('queue_message', 'referal_need')
    # ### end Alembic commands ###
