"""add queue

Revision ID: 9c2570d963b1
Revises: 2e00c892127b
Create Date: 2020-10-26 11:59:03.883926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2570d963b1'
down_revision = '2e00c892127b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
