"""add is_end

Revision ID: a606c9d7d3fa
Revises: ae5e8398ade7
Create Date: 2020-10-28 19:35:29.022243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a606c9d7d3fa'
down_revision = 'ae5e8398ade7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_end', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_end')
    # ### end Alembic commands ###
