"""add queue

Revision ID: c9f4818e2073
Revises: eb33ce5b86d2
Create Date: 2020-10-26 11:59:14.004296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f4818e2073'
down_revision = 'eb33ce5b86d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
