"""add queue

Revision ID: eb33ce5b86d2
Revises: 9c2570d963b1
Create Date: 2020-10-26 11:59:08.986901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb33ce5b86d2'
down_revision = '9c2570d963b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
