"""add queue

Revision ID: f4ddf75333f7
Revises: 21bc3fcd1b7b
Create Date: 2020-10-26 11:59:40.407344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ddf75333f7'
down_revision = '21bc3fcd1b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
