version: "3"

services:    
    bot:
      build: tgame_engine/
      container_name: bot
      command: poetry run gunicorn app:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
      environment:
        - APP_URL=
        - BOT_TOKEN=
      networks:
        intranet:
          aliases:
            - bot-app

    nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./dhparam:/etc/nginx/dhparam
        - ./certbot/conf/:/etc/nginx/ssl/
        - ./certbot/data:/usr/share/nginx/html/letsencrypt
      ports:
        - 5000:5000
      networks:
        - intranet
      depends_on:
        - bot
      
    certbot:
       image: certbot/certbot:latest
       command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email email@email.com --agree-tos --no-eff-email -d domain.ru
       volumes:
         - ./certbot/conf/:/etc/letsencrypt
         - ./certbot/logs/:/var/log/letsencrypt
         - ./certbot/data:/usr/share/nginx/html/letsencrypt

networks: 
  intranet: